package minidb;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import minidb.storage.BufferPool;
import minidb.storage.FileDiskManager;
import minidb.storage.FifoBufferPool;
import minidb.storage.LruBufferPool;
import minidb.storage.StorageException;

/** Reads the JSON generated by minisql_plan_json from stdin and prints execution results. */
public final class Main {
    private Main() { }
    public static void main(String[] args) throws IOException {
        if (args.length == 1 && args[0].equalsIgnoreCase("web")) {
            WebServer server = WebServer.startFromSystemProperties();
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                try { server.close(); }
                catch (RuntimeException ignored) { }
            }, "minidb-web-shutdown"));
            String url = "http://localhost:" + server.port();
            System.out.printf("MiniDB Web 演示台已启动：%s%n", url);
            if (Boolean.getBoolean("minidb.web.openBrowser")) openBrowser(url);
            return;
        }
        if (args.length == 1 && args[0].equalsIgnoreCase("sql")) {
            String compilerPath = System.getProperty("minidb.compiler.path");
            if (compilerPath == null || compilerPath.isBlank()) throw new IOException("Missing -Dminidb.compiler.path");
            String sql = new String(System.in.readAllBytes(), StandardCharsets.UTF_8);
            try (PageRecordStore store = openPersistent()) {
                DatabaseEngine engine = new DatabaseEngine(store);
                SqlCompilerRunner.CompilerOutput compiled = new ProcessSqlCompilerRunner(Path.of(compilerPath), java.time.Duration.ofSeconds(10)).compile(sql, engine.catalogSnapshotFileText());
                if (compiled.exitCode() != 0) throw new IOException(compiled.stderr());
                for (DatabaseEngine.ExecutionResult result : engine.executeProgramJson(compiled.stdout())) print(result);
            }
            return;
        }
        if (args.length == 1 && args[0].equalsIgnoreCase("reset")) {
            Path file = Path.of(System.getProperty("minidb.data.path", "data/minidb.db"));
            Files.deleteIfExists(file);
            Files.deleteIfExists(Path.of(file + ".alloc"));
            System.out.println("MiniDB persistent data reset.");
            return;
        }
        if (args.length != 0) {
            System.err.println("Usage: java -jar minidb-engine.jar [web|sql|reset]");
            System.exit(2);
        }
        String json = new String(System.in.readAllBytes(), StandardCharsets.UTF_8);
        try {
            List<DatabaseEngine.ExecutionResult> results = new DatabaseEngine().executeProgramJson(json);
            for (DatabaseEngine.ExecutionResult result : results) print(result);
        } catch (EngineException | IllegalArgumentException error) {
            if (error instanceof EngineException engine && engine.line() != null)
                System.err.printf("ExecutionError [%s] at line %d, column %d: %s%n", engine.code(), engine.line(), engine.column(), engine.getMessage());
            else if (error instanceof EngineException engine)
                System.err.printf("ExecutionError [%s]: %s%n", engine.code(), engine.getMessage());
            else System.err.println("ProtocolError: " + error.getMessage());
            System.exit(1);
        }
    }
    private static PageRecordStore openPersistent() throws IOException {
        try {
            Path database = Path.of(System.getProperty("minidb.data.path", "data/minidb.db"));
            int frames = Integer.parseInt(System.getProperty("minidb.buffer.frames", "64"));
            BufferPool pool = System.getProperty("minidb.buffer.policy", "LRU").equalsIgnoreCase("FIFO")
                ? new FifoBufferPool(frames, new FileDiskManager(database)) : new LruBufferPool(frames, new FileDiskManager(database));
            return new PageRecordStore(pool);
        } catch (StorageException error) { throw new IOException("could not open persistent MiniDB storage", error); }
    }
    private static void openBrowser(String url) {
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) Desktop.getDesktop().browse(URI.create(url));
            else System.err.println("浏览器未自动打开，请手动访问：" + url);
        } catch (Exception error) {
            System.err.println("浏览器未自动打开，请手动访问：" + url);
        }
    }
    private static void print(DatabaseEngine.ExecutionResult result) {
        if (result instanceof DatabaseEngine.CommandResult command) {
            System.out.printf("%s affected=%d%n", command.operation(), command.affectedRows());
            return;
        }
        DatabaseEngine.QueryResult query = (DatabaseEngine.QueryResult) result;
        System.out.println(String.join(" | ", query.columns()));
        for (List<Object> row : query.rows()) System.out.println(row.stream().map(String::valueOf).reduce((a, b) -> a + " | " + b).orElse(""));
        System.out.printf("%d row(s)%n", query.rows().size());
    }
}
