package minidb;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.List;

/** Reads the JSON generated by minisql_plan_json from stdin and prints execution results. */
public final class Main {
    private Main() { }
    public static void main(String[] args) throws IOException {
        if (args.length == 1 && args[0].equalsIgnoreCase("web")) {
            WebServer server = WebServer.startFromSystemProperties();
            String url = "http://localhost:" + server.port();
            System.out.printf("MiniDB Web 演示台已启动：%s%n", url);
            if (Boolean.getBoolean("minidb.web.openBrowser")) openBrowser(url);
            return;
        }
        if (args.length != 0) {
            System.err.println("Usage: java -jar minidb-engine.jar [web]");
            System.exit(2);
        }
        String json = new String(System.in.readAllBytes(), StandardCharsets.UTF_8);
        try {
            List<DatabaseEngine.ExecutionResult> results = new DatabaseEngine().executeProgramJson(json);
            for (DatabaseEngine.ExecutionResult result : results) print(result);
        } catch (EngineException | IllegalArgumentException error) {
            if (error instanceof EngineException engine && engine.line() != null)
                System.err.printf("ExecutionError [%s] at line %d, column %d: %s%n", engine.code(), engine.line(), engine.column(), engine.getMessage());
            else if (error instanceof EngineException engine)
                System.err.printf("ExecutionError [%s]: %s%n", engine.code(), engine.getMessage());
            else System.err.println("ProtocolError: " + error.getMessage());
            System.exit(1);
        }
    }
    private static void openBrowser(String url) {
        try {
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) Desktop.getDesktop().browse(URI.create(url));
            else System.err.println("浏览器未自动打开，请手动访问：" + url);
        } catch (Exception error) {
            System.err.println("浏览器未自动打开，请手动访问：" + url);
        }
    }
    private static void print(DatabaseEngine.ExecutionResult result) {
        if (result instanceof DatabaseEngine.CommandResult command) {
            System.out.printf("%s affected=%d%n", command.operation(), command.affectedRows());
            return;
        }
        DatabaseEngine.QueryResult query = (DatabaseEngine.QueryResult) result;
        System.out.println(String.join(" | ", query.columns()));
        for (List<Object> row : query.rows()) System.out.println(row.stream().map(String::valueOf).reduce((a, b) -> a + " | " + b).orElse(""));
        System.out.printf("%d row(s)%n", query.rows().size());
    }
}
